### Name: Mowleen Armstrong

# 100 numpy exercises
This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)

1.26.4


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
import numpy as np
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
memory_size = arr.nbytes
print(f"Memory size of the array: {memory_size} bytes")

Memory size of the array: 40 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
import numpy as np
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
import numpy as np
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
import numpy as np
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
import numpy as np
arr = np.arange(10, 50)
reversed_arr = arr[::-1]
print(reversed_arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
import numpy as np
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
import numpy as np
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
import numpy as np
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
import numpy as np
random_array = np.random.random((3, 3, 3))
print(random_array)

[[[0.61593368 0.57766277 0.06377085]
  [0.04993834 0.51815094 0.16917044]
  [0.06761084 0.90141286 0.17671178]]

 [[0.32781833 0.18370658 0.77427212]
  [0.7834338  0.71026211 0.97487765]
  [0.11826099 0.94564439 0.71548711]]

 [[0.39606865 0.00545978 0.16930175]
  [0.29645133 0.31640767 0.84872098]
  [0.14024644 0.57580489 0.92419745]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
import numpy as np
random_10x10 = np.random.random((10, 10))
min_value = np.min(random_10x10)
max_value = np.max(random_10x10)
print(f"Minimum value: {min_value}")
print(f"Maximum value: {max_value}")

Minimum value: 0.0006178202951684364
Maximum value: 0.9902769941865649


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
import numpy as np
random_vector = np.random.random(30)
mean_value = np.mean(random_vector)
print(f"Mean value: {mean_value}")

Mean value: 0.46915066779206427


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
import numpy as np
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_with_border = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(array_with_border)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
import numpy as np
print("0 * np.nan:", 0 * np.nan)
print("np.nan == np.nan:", np.nan == np.nan)
print("np.inf > np.nan:", np.inf > np.nan)
print("np.nan - np.nan:", np.nan - np.nan)
print("np.nan in set([np.nan]):", np.nan in set([np.nan]))
print("0.3 == 3 * 0.1:", 0.3 == 3 * 0.1)

0 * np.nan: nan
np.nan == np.nan: False
np.inf > np.nan: False
np.nan - np.nan: nan
np.nan in set([np.nan]): True
0.3 == 3 * 0.1: False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
import numpy as np
matrix = np.diag([1, 2, 3, 4], k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
import numpy as np
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
import numpy as np
shape = (6, 7, 8)
index = np.unravel_index(100, shape)
print(f"The index of the 100th element is: {index}")

The index of the 100th element is: (1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
import numpy as np
checkerboard = np.tile([[0, 1], [1, 0]], (4, 4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
import numpy as np
random_matrix = np.random.random((5, 5))
normalized_matrix = (random_matrix - np.min(random_matrix)) / (np.max(random_matrix) - np.min(random_matrix))
print(normalized_matrix)

[[0.85454323 0.04089093 0.79284369 0.         0.07646871]
 [0.79094008 0.79995506 0.21688464 0.92669214 0.38928147]
 [0.87791361 0.34867816 1.         0.18535934 0.2218292 ]
 [0.3669345  0.14165725 0.40135449 0.61322256 0.83827084]
 [0.31724247 0.5236723  0.7403216  0.33769133 0.02520125]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
import numpy as np
rgba_dtype = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])
color = np.array([(255, 0, 0, 255)], dtype=rgba_dtype)
print(color)

[(255, 0, 0, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
import numpy as np
matrix_5x3 = np.random.random((5, 3))
matrix_3x2 = np.random.random((3, 2))
result = np.dot(matrix_5x3, matrix_3x2)
print(result)

[[0.8527623  0.87763899]
 [0.36644135 0.61877732]
 [0.553946   0.60509613]
 [0.94096356 0.62896179]
 [0.83739969 0.46729853]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Negate all elements between 3 and 8 (inclusive)
arr[(arr > 3) & (arr < 8)] *= -1

print(arr)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
import numpy as np
Z = np.array([1, 2, 3, 4, 5])
print("Z**Z:", Z**Z)
print("2 << Z >> 2:", 2 << Z >> 2)
print("1j * Z:", 1j * Z)
print("Z / 1 / 1:", Z / 1 / 1)

Z**Z: [   1    4   27  256 3125]
2 << Z >> 2: [ 1  2  4  8 16]
1j * Z: [0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
Z / 1 / 1: [1. 2. 3. 4. 5.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
import numpy as np
Z = np.array([1,2,3,4,5, 3.566, 4.786])
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\Mowleen\AppData\Local\Temp\ipykernel_8436\220191003.py:3: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Mowleen\AppData\Local\Temp\ipykernel_8436\220191003.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Mowleen\AppData\Local\Temp\ipykernel_8436\220191003.py:5: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
import numpy as np

arr = np.array([-1.5, 1.5, -2.7, 2.3])
rounded_arr = np.sign(arr) * np.ceil(np.abs(arr))
print(rounded_arr)

[-2.  2. -3.  3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 5, 6, 7, 8])

common_values = np.intersect1d(arr1, arr2)
print(common_values)

[4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
import numpy as np
np.seterr(all='ignore')
print(np.array(0) / np.array(0))

nan


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
from datetime import datetime, timedelta

today = datetime.today().date()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2025-04-01
Today: 2025-04-02
Tomorrow: 2025-04-03


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
import numpy as np

start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-07-31')

dates = np.arange(start_date, end_date + np.timedelta64(1, 'D'), dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

A = A.astype(float)
A += B
A *= -0.5
print(A)

[-2.5 -3.5 -4.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
import numpy as np

arr = np.random.rand(10) * 10
print("Original array:", arr)

method1 = np.floor(arr)

method2 = np.trunc(arr)

method3 = arr.astype(int)

method4 = arr // 1

print("Method 1 (np.floor):", method1)
print("Method 2 (np.trunc):", method2)
print("Method 3 (astype(int)):", method3)
print("Method 4 (// 1):", method4)

Original array: [9.26403928 1.82407393 8.61688389 1.74009735 9.44984514 4.06933985
 9.35245568 8.46392869 7.64958052 9.2983938 ]
Method 1 (np.floor): [9. 1. 8. 1. 9. 4. 9. 8. 7. 9.]
Method 2 (np.trunc): [9. 1. 8. 1. 9. 4. 9. 8. 7. 9.]
Method 3 (astype(int)): [9 1 8 1 9 4 9 8 7 9]
Method 4 (// 1): [9. 1. 8. 1. 9. 4. 9. 8. 7. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
import numpy as np
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
import numpy as np
def generate_integers(n):
    for i in range(n):
        yield i

gen = generate_integers(10)
arr = np.array(list(gen))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
import numpy as np
arr = np.linspace(0, 1, 12)[1:-1]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
import numpy as np
random_vector = np.random.rand(10)

sorted_vector = np.sort(random_vector)

print("Original vector:", random_vector)
print("Sorted vector:", sorted_vector)

Original vector: [0.64198157 0.68034877 0.56996582 0.2302694  0.11022089 0.6437277
 0.73328718 0.7427826  0.38257538 0.72511069]
Sorted vector: [0.11022089 0.2302694  0.38257538 0.56996582 0.64198157 0.6437277
 0.68034877 0.72511069 0.73328718 0.7427826 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = sum(arr)
print(result)

15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
import numpy as np

A = np.random.rand(5)
B = np.random.rand(5)

are_equal = np.array_equal(A, B)
print("Arrays are equal:", are_equal)

Arrays are equal: False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
import numpy as np

arr = np.random.rand(5)

arr.flags.writeable = False
try:
    arr[0] = 10
except ValueError as e:
    print(f"Error: {e}")

Error: assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
import numpy as np
cartesian_coords = np.random.rand(10, 2) * 10

x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

polar_coords = np.column_stack((r, theta))

print("Cartesian coordinates:\n", cartesian_coords)
print("Polar coordinates (r, theta):\n", polar_coords)

Cartesian coordinates:
 [[9.02803202 5.43609759]
 [4.92335568 9.38252241]
 [9.7415989  4.21246951]
 [4.27370956 3.57428302]
 [0.63276425 8.02093808]
 [9.45634455 3.22975427]
 [5.60240203 5.79067731]
 [5.51492159 9.94913928]
 [7.54780314 3.71930819]
 [4.98178181 3.71376657]]
Polar coordinates (r, theta):
 [[10.53833569  0.54198816]
 [10.59580851  1.0875556 ]
 [10.61337121  0.40813926]
 [ 5.57136361  0.69651129]
 [ 8.04585846  1.49207031]
 [ 9.99268557  0.32912153]
 [ 8.0572236   0.80192207]
 [11.37540032  1.06464903]
 [ 8.41442723  0.45784447]
 [ 6.21371162  0.6405953 ]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
import numpy as np

vector = np.random.rand(10)

vector[vector.argmax()] = 0

print("Original vector:", vector)

Original vector: [0.62106509 0.66573339 0.80417758 0.         0.81600231 0.84639886
 0.89367683 0.89354928 0.40358282 0.32965043]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [2]:
import numpy as np
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
Z


array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [3]:
import numpy as np
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


3638.163637117973


In [4]:
import numpy as np

#### 49. How to print all the values of an array? (★★☆)

In [5]:
arr = np.array([1, 2, 3, 4, 5])  # Example array
arr


array([1, 2, 3, 4, 5])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [6]:
vector = np.array([1, 3, 5, 7, 9])
scalar = 6

closest_value = vector[np.argmin(np.abs(vector - scalar))]
closest_value


np.int64(5)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [7]:
import numpy as np

# Create a structured array with fields for position (x, y) and color (r, g, b)
Z = np.zeros(10, dtype={'names': ('position', 'color'),
                          'formats': (np.float64, (np.uint8, 3))})
Z


array([(0., [0, 0, 0]), (0., [0, 0, 0]), (0., [0, 0, 0]), (0., [0, 0, 0]),
       (0., [0, 0, 0]), (0., [0, 0, 0]), (0., [0, 0, 0]), (0., [0, 0, 0]),
       (0., [0, 0, 0]), (0., [0, 0, 0])],
      dtype=[('position', '<f8'), ('color', 'u1', (3,))])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [8]:
import numpy as np

# Create a random vector with shape (100, 2) representing coordinates
coords = np.random.rand(100, 2)

# Calculate the squared differences between all pairs of points
diffs = np.sum((coords[:, np.newaxis, :] - coords[np.newaxis, :, :]) ** 2, axis=2)

# Take the square root to get the distances
distances = np.sqrt(diffs)

distances


array([[0.        , 0.37374509, 0.29811211, ..., 0.65940657, 0.47200042,
        0.30930752],
       [0.37374509, 0.        , 0.31658341, ..., 0.63482038, 0.36362272,
        0.08104638],
       [0.29811211, 0.31658341, 0.        , ..., 0.37891718, 0.1776752 ,
        0.31809771],
       ...,
       [0.65940657, 0.63482038, 0.37891718, ..., 0.        , 0.27215973,
        0.66721846],
       [0.47200042, 0.36362272, 0.1776752 , ..., 0.27215973, 0.        ,
        0.40224098],
       [0.30930752, 0.08104638, 0.31809771, ..., 0.66721846, 0.40224098,
        0.        ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [10]:
# Create a float32 array
float_array = np.array([1.5, 2.7, 3.2, 4.9], dtype=np.float32)

# Convert the float32 array to int32 in place
int_array = float_array.astype(np.int32, copy=False)

int_array


array([1, 2, 3, 4], dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [9]:
from io import StringIO

# Create a StringIO object to simulate the file
file_content = """1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11"""
file_like_object = StringIO(file_content)

# Read the file using numpy's genfromtxt function
data = np.genfromtxt(file_like_object, delimiter=",", dtype=int)

data

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [11]:
# Using np.ndenumerate():
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)

# Using np.ndindex():
Z = np.arange(9).reshape(3,3)
for index in np.ndindex(Z.shape):
    print(index, Z[index])


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [12]:
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
d = np.sqrt(x * x + y * y)
sigma, mu = 1.0, 0.0
gauss = np.exp(-((d - mu) ** 2 / (2.0 * sigma ** 2)))
gauss


array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [14]:
import numpy as np

def randomly_place_elements(shape, p):
    """Randomly places p elements in a 2D array of the given shape.

    Args:
        shape: A tuple (rows, cols) specifying the dimensions of the array.
        p: The number of elements to place.

    Returns:
        A 2D NumPy array with p elements randomly placed, or None if p is invalid.
    """

    rows, cols = shape
    if p < 0 or p > rows * cols:
        print("Error: Invalid number of elements to place.")
        return None

    array = np.zeros(shape, dtype=int)  # Initialize with zeros
    indices = np.random.choice(rows * cols, size=p, replace=False)  # Random indices without replacement
    row_indices, col_indices = np.unravel_index(indices, shape)  # Convert linear indices to row, col indices
    array[row_indices, col_indices] = 1  # Place elements (value=1 in this example)

    return array

# Example usage:
shape = (5, 5)
p = 7
result_array = randomly_place_elements(shape, p)

if result_array is not None:
  result_array


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [15]:
matrix = np.random.rand(3, 4)  # Example 3x4 matrix
print("Original matrix:")
print(matrix)

row_means = np.mean(matrix, axis=1, keepdims=True)
print("\nRow means:")
print(row_means)


result_matrix = matrix - row_means
print("\nMatrix with row means subtracted:")
result_matrix


Original matrix:
[[0.97390284 0.64241014 0.31555076 0.99437215]
 [0.38159086 0.91025632 0.18295148 0.87263088]
 [0.01568216 0.32373144 0.80567687 0.56706634]]

Row means:
[[0.73155897]
 [0.58685738]
 [0.4280392 ]]

Matrix with row means subtracted:


array([[ 0.24234387, -0.08914883, -0.41600821,  0.26281318],
       [-0.20526652,  0.32339893, -0.40390591,  0.2857735 ],
       [-0.41235704, -0.10430776,  0.37763767,  0.13902714]])

#### 59. How to sort an array by the nth column? (★★☆)

In [16]:
import numpy as np

# Example array
array = np.array([[1, 5, 2],
                  [3, 1, 4],
                  [2, 3, 1]])

# Specify the column to sort by (e.g., the second column, index 1)
n = 1

# Sort the array by the nth column
sorted_array = array[array[:, n].argsort()]

print("Original array:\n", array)
print("\nSorted array by the", n, "th column:\n", sorted_array)


Original array:
 [[1 5 2]
 [3 1 4]
 [2 3 1]]

Sorted array by the 1 th column:
 [[3 1 4]
 [2 3 1]
 [1 5 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [17]:
def has_null_columns(array_2d):
    """
    Checks if a given 2D NumPy array has any columns containing only null values (NaN).

    Args:
    array_2d: The 2D NumPy array to check.

    Returns:
    True if any columns are null, False otherwise.
    """

    # Check if the input is a 2D NumPy array
    if not isinstance(array_2d, np.ndarray) or array_2d.ndim != 2:
        raise ValueError("Input must be a 2D NumPy array.")

    # Check for null columns (all NaN)
    null_columns = np.all(np.isnan(array_2d), axis=0)  # Check along each column

    return np.any(null_columns)  # Check if at least one column is all NaN

# Example usage
array_with_null = np.array([[1, 2, np.nan],
                         [4, np.nan, np.nan],
                         [7, 8, np.nan]])

array_without_null = np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]])

print("Array with null columns:", has_null_columns(array_with_null)) # True
print("Array without null columns:", has_null_columns(array_without_null)) # False


Array with null columns: True
Array without null columns: False


#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)